package config

import (
	"os"
	"path/filepath"

	"github.com/google/uuid"
	"github.com/spf13/viper"
)

const (
	AppName = "contextsync"
)

var (
	configDir string
	dataDir   string
)

// Init initializes configuration
func Init() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	configDir = filepath.Join(home, ".contextsync")
	dataDir = filepath.Join(configDir, "data")

	// Create directories
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return err
	}

	// Setup viper
	viper.SetConfigName("config")
	viper.SetConfigType("json")
	viper.AddConfigPath(configDir)

	// Set defaults
	viper.SetDefault("device_id", uuid.New().String())
	viper.SetDefault("server_url", "https://contextsync.yangqing.one")

	// Read config
	if err := viper.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); ok {
			// Create default config
			viper.SafeWriteConfig()
		}
	}

	return nil
}

// SetConfigFile sets a specific config file
func SetConfigFile(path string) {
	viper.SetConfigFile(path)
}

// CreateDirectories creates all required directories
func CreateDirectories() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	dirs := []string{
		filepath.Join(home, ".contextsync"),
		filepath.Join(home, ".contextsync", "data"),
		filepath.Join(home, ".contextsync", "backups"),
		filepath.Join(home, ".contextsync", "logs"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}

	return nil
}

// GetConfigDir returns the config directory
func GetConfigDir() string {
	return configDir
}

// GetDataPath returns the database path
func GetDataPath() string {
	return filepath.Join(dataDir, "memories.db")
}

// GetRulesPath returns the rules file path
func GetRulesPath() string {
	return filepath.Join(configDir, "rules.md")
}

// GetServerURL returns the server URL for API calls
func GetServerURL() string {
	return viper.GetString("server_url")
}

// GetDeviceID returns the device ID
func GetDeviceID() string {
	return viper.GetString("device_id")
}

// Get returns a config value
func Get(key string) interface{} {
	return viper.Get(key)
}

// Set sets a config value
func Set(key string, value interface{}) {
	viper.Set(key, value)
	viper.WriteConfig()
}

// ==================== Account Methods ====================

// GetAccountID returns the logged-in account ID
func GetAccountID() string {
	return viper.GetString("account_id")
}

// GetAccountEmail returns the logged-in account email
func GetAccountEmail() string {
	return viper.GetString("account_email")
}

// GetAuthToken returns the authentication token
func GetAuthToken() string {
	return viper.GetString("auth_token")
}

// IsLoggedIn returns true if user is logged in
func IsLoggedIn() bool {
	return GetAccountID() != "" && GetAuthToken() != ""
}

// SetAccount sets the account information after login
func SetAccount(accountID, email, token string) {
	viper.Set("account_id", accountID)
	viper.Set("account_email", email)
	viper.Set("auth_token", token)
	viper.WriteConfig()
}

// ClearAccount clears the account information on logout
func ClearAccount() {
	viper.Set("account_id", "")
	viper.Set("account_email", "")
	viper.Set("auth_token", "")
	viper.WriteConfig()
}

// CreateDefaultRules creates the default rules file
func CreateDefaultRules() error {
	rulesPath := GetRulesPath()

	// Check if exists
	if _, err := os.Stat(rulesPath); err == nil {
		return nil // Already exists
	}

	defaultRules := `# My Coding Rules

> This file is the single source of truth for all your AI coding tools.
> ContextSync will automatically sync these rules to all configured tools.

## Language & Framework

- Always use TypeScript, never plain JavaScript
- Use Zod for schema validation
- Prefer functional components in React

## Code Style

- Max line length: 100 characters
- Use named exports, avoid default exports
- Always add JSDoc comments to public functions

## Architecture Decisions

- Use repository pattern for data access
- No direct database calls in controllers
- Prefer composition over inheritance

---

_Generated by ContextSync_
`

	return os.WriteFile(rulesPath, []byte(defaultRules), 0644)
}
